# 机械臂的配置文件

# 串口设备号
# - Ubuntu 操作系统
#device: '/dev/ttyUSB0'
# - Windows 操作系统
device: '/dev/rikiservo'


joint2servo:
  k: [-58.251, 56.405, -54.431, -58.760, 55.895]
  b: [1.200, 86.000, -6.500, -0.400, 0.400]
  
# Pitch平面拟合结果
pitch_panel:
  a: -0.002490
  b: -0.004985
  c: 3.048636

# 位姿列表
# - 注: 存放的是关节角度，单位°
pose_dict:
  'home': [ 0, -120,  60,  110,  0]
  'capture_image': [-3.8, -130.4, 98.8, 94.7, 0]
  'object_release': [48.2, -107.4, 94.0, 46.0, -180.0]
  'line_detect': [-1.3, -123.3, 98.8, 82.4, -60]
