#############################
## 相机的默认参数
############################# 
# 摄像头的设备号
# 默认为 0:  对应Ubuntu系统中的 /dev/video0
device: 0
# 画面宽度
img_width: 1920
#img_width: 640
# 画面高度 
img_height: 1080
#img_height: 480
# 相机帧率
fps: 30
# 图像缓冲区的尺寸
buffer_size: 2