abot_detect_node:
    model_path: "/home/abot/catkin_ws/src/abot_project/abot_object_trtdetect/config/ssd-mobilenet.onnx"
    class_labels_path: "/home/abot/catkin_ws/src/abot_project/abot_object_trtdetect/config/labels.txt"

