# 手眼标定九点法相关配置
# - 九点标定板的尺寸，以实际测量为准
#   - 宽度，单位mm 
#     P0-P2的直线距离
board_width : 120
#   - 高度, 单位mm
#     P0-P6的直线距离
board_height : 85 
# - 机械臂延长杆的尺寸, 单位mm
#   末端为尖端，方便采集数据，可以尖头铅笔。
#   该配置文件以实际测量为准
#   如果没有延长杆就是0
pencil_length : 0
