# 机械臂的配置文件

# 串口设备号
# - Ubuntu 操作系统
#device: '/dev/ttyUSB0'
# - Windows 操作系统
device: '/dev/rikibase'


joint2servo:
  k: [-56.277, -55.768, -56.341, -60.352, 57.996]
  b: [-0.100, -87.200, -1.900, -1.100, -1.000]

# Pitch平面拟合结果
pitch_panel:
  a: -0.002490
  b: -0.004985
  c: 3.048636

# 位姿列表
# - 注: 存放的是关节角度，单位°
pose_dict:
  'home': [ 0, -90,  30,  135,  0]
  'capture_image': [-3.8, -130.4, 98.8, 94.7, 0]
  'object_release': [48.2, -107.4, 94.0, 46.0, -180.0]
  'line_detect': [-1.3, -123.3, 98.8, 82.4, -60]
