#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Authors: Rikibot kevin

import rospy
import os
import math
import numpy as np
import cv2
import time
import json
from std_msgs.msg import UInt8, Float64
from vision_msgs.msg import BoundingBox2D, Detection2DArray,ObjectHypothesisWithPose,Detection2D
from sensor_msgs.msg import Image, CompressedImage
from dynamic_reconfigure.server import Server
from abot_xarm.cfg import XarmPoseParamsConfig
from actionlib_msgs.msg import *
from geometry_msgs.msg import Pose, Point, Quaternion
from abot_xarm_driver import *
from abot_nav import *


GRIPPER_CLOSE = 700
GRIPPER_OPEN = 150
GRIPPER_DEFAULT = 500

class AbotxArmGrasp():
    def __init__(self):
        self.x = rospy.get_param("~x", 40)
        self.y = rospy.get_param("~y", 0) 
        self.z = rospy.get_param("~z", 230)
        self.rotary = rospy.get_param("~rotary", 90)

        self.speed = rospy.get_param("~speed", 1000)  #Servo contorl speed ms
        self.port = rospy.get_param("~port", '/dev/ttyACM0')
        self.baud = rospy.get_param("~baud", 115200)

        self.detect_mode = rospy.get_param("~detect_mode", 'hsv')
        self.fix_grasp_mode = rospy.get_param("~fix_grasp_mode", True)
        self.is_calibration_mode = rospy.get_param("~is_detection_calibration_mode", False)
        self.calib_data = rospy.get_param("~calib_data", [55, -58, 513, 190, -65, -30])

        self.postion_offset = rospy.get_param("~postion_offset", 0.2)
        self.obj_grasp_pose =  rospy.get_param("~obj_grasp_pose", '3.552, -1.372, 0.000')
        self.obj_grasp_quat =  rospy.get_param("~obj_grasp_quat", '0.000, 0.000, 1.000, 0.010')
        self.obj_place_pose = rospy.get_param("~obj_place_pose", '-0.049,  -0.853, 0')
        self.obj_place_quat = rospy.get_param("~obj_place_quat", '0.000, 0.000, -0.024, 1.000')

        self.servo_x = rospy.get_param("~servo_x", 10)
        os.system("rostopic pub -1 servo riki_msgs/Servo -- '90' '%d'" %(self.servo_x))

        rospy.Subscriber("/object_point_info", Detection2D, self.ObjectCallback)

        self.last_x = self.last_y = self.last_z = self.last_rotary = 0
        self.grasp_lock = False
        self.goal_lock = False
        self.obj_cnt = 0
        self.obj_ok = 10
        self.object_pose = None

        self.k = 0.2

        self.offset_x = self.calib_data[3] + self.calib_data[1] 
        self.offset_y = self.calib_data[4] + self.calib_data[0]
        self.offset_z = self.calib_data[2]  + self.calib_data[5]
        rospy.loginfo("x: %d, y: %d, z: %d", self.offset_x, self.offset_y, self.offset_z)


        r = rospy.Rate(5)
        rospy.on_shutdown(self.shutdown)


        if self.is_calibration_mode is True:
            srv_xarm = Server(XarmPoseParamsConfig, self.cbGetxArmPoseParam)

 
        self.xArmCtrl = RikibotxArmCtrl(port=self.port, baud=self.baud)


        self.nav_step = 0
        grasp_pose = list(map(float, self.obj_grasp_pose.split(',')))
        grasp_quat = list(map(float, self.obj_grasp_quat.split(',')))
        place_pose = list(map(float, self.obj_place_pose.split(',')))
        place_quat = list(map(float, self.obj_place_quat.split(',')))
        self.GraspGoalOffset = Pose(Point(grasp_pose[0] - self.postion_offset, grasp_pose[1], grasp_pose[2]), Quaternion(grasp_quat[0], grasp_quat[1], grasp_quat[2], grasp_quat[3]))
        self.GraspGoal = Pose(Point(grasp_pose[0], grasp_pose[1], grasp_pose[2]), Quaternion(grasp_quat[0], grasp_quat[1], grasp_quat[2], grasp_quat[3]))
        self.PlaceGoalOffset = Pose(Point(place_pose[0] + self.postion_offset, place_pose[1], place_pose[2]), Quaternion(place_quat[0], place_quat[1], place_quat[2], place_quat[3]))
        self.PlaceGoal = Pose(Point(place_pose[0], place_pose[1], place_pose[2]), Quaternion(place_quat[0], place_quat[1], place_quat[2], place_quat[3]))

       
        if self.fix_grasp_mode is False and self.is_calibration_mode is False:
            rospy.loginfo("start navigation move to grasp pos")
            self.nav = RikibotNav()

        if self.is_calibration_mode is False:
            self.xArmHome()

        self.xArmGripperTxData(GRIPPER_OPEN)


        while not rospy.is_shutdown():
            if self.is_calibration_mode is True:
                if self.last_x != self.x or self.last_y != self.y or self.last_z != self.z or self.last_rotary != self.rotary:
                    rospy.loginfo("Update Pose")
                    self.last_x = self.x
                    self.last_y = self.y
                    self.last_z = self.z
                    self.last_rotary = self.rotary
                    if self.object_pose is not None:
                        rospy.loginfo("current object pose: %d, %d, %d, current arm pose: %d, %d, %d", 
                                self.object_pose.x, self.object_pose.y, self.object_pose.z,
                                self.x, self.y, self.z)
                    else:
                        rospy.loginfo("current arm pose: %d, %d, %d", self.x, self.y, self.z)
                    self.xArmPoseTxData(self.x, self.y, self.z, self.rotary)
            else:
                if self.fix_grasp_mode is False:
                    if self.goal_lock is True:
                        if self.grasp_lock is True:
                            self.xArmGraspPlan()
                    else:
                        rospy.loginfo("start navigtion and move grasp object")
                        self.MoveSingleGrasp()
                else:
                    if self.grasp_lock is True:
                        self.xArmGraspPlan()

            r.sleep()

    def ObjectCallback(self, object_msg):
        self.object_info = object_msg
        self.object_pose = self.object_info.results[0].pose.pose.position
        if self.object_pose.z != 0:
            self.obj_cnt = self.obj_cnt + 1
        #print(self.object_info.results[0].pose.pose.position)
        if self.obj_cnt > self.obj_ok and self.grasp_lock is False:
            self.grasp_lock = True

    def CameraiPointToGraspPose(self):
        self.x = self.offset_x - self.object_pose.y - abs(self.calib_data[2]-self.object_pose.z)*self.k
        if self.object_pose.x > 0:
            self.y = self.offset_y - self.object_pose.x
        else:
            self.y = -self.offset_y - self.object_pose.x
        self.z = self.offset_z - self.object_pose.z
        rospy.loginfo("current obj x: %d, y: %d, z: %d, grasp pose: x: %d, y: %d, z: %d", 
                self.object_pose.x, self.object_pose.y, self.object_pose.z, self.x, self.y, self.z)


    def MoveSingleGrasp(self):
        if self.nav_step == 0:
            self.nav.SendGoal(self.GraspGoalOffset)
        if self.nav_step == 1:
            self.nav.SendGoal(self.GraspGoal)
        if self.nav_step == 2 and self.grasp_finish is True:
            self.nav.SendGoal(self.PlaceGoalOffset)
        if self.nav_step == 3:
            self.nav.SendGoal(self.PlaceGoal)
        if self.nav_step == 4:
            self.xArmPlacePlan()
            
        state =self.nav.NavState()
        if state == 1:
            self.nav_step = self.nav_step + 1
            if self.nav_step == 2:
                self.goal_lock  = True

    def xArmGraspPlan(self):
        self.CameraiPointToGraspPose()
        time.sleep(1)
        self.xArmPoseTxData(self.x, self.y, self.z, self.rotary)
        time.sleep(2)
        self.xArmGripperTxData(GRIPPER_CLOSE)
        time.sleep(2)
        self.xArmPoseTxData(40, 0, 230)
        time.sleep(2)
        if self.fix_grasp_mode is True:
            self.xArmGripperTxData(GRIPPER_OPEN)
            time.sleep(2)
            self.xArmHome()
            time.sleep(2)
        self.grasp_lock = False
        self.goal_lock = False
        self.grasp_finish = True
        self.obj_cnt = 0

    def xArmPlacePlan(self):
        self.xArmPoseTxData(250, 0, 50)
        time.sleep(2)
        self.xArmGripperTxData(GRIPPER_OPEN)
        time.sleep(2)
        self.xArmHome()
        time.sleep(2)

    def cbGetxArmPoseParam(self, config, level):
        rospy.loginfo("Rikibot Xarm Pose Calib")
        rospy.loginfo("x : %d", config.x)
        rospy.loginfo("y : %d", config.y)
        rospy.loginfo("z : %d", config.z)
        rospy.loginfo("rotary : %d", config.rotary)

        self.x = config.x
        self.y = config.y
        self.z = config.z
        self.rotary = config.rotary
        return config


    def xArmPoseTxData(self, x, y, z, rotary=90):
        xArmPose = {"RikibotxArmCmd": 1,"Pose": {"x": x, "y": y, "z": z, "rotary": rotary},"time": self.speed}
        self.xArmCtrl.SerialWriteData(json.dumps(xArmPose))

    def xArmGripperTxData(self, gripper_step):
        xArmGripper = {"RikibotxArmCmd": 2, "Gripper": gripper_step, "time": self.speed }
        self.xArmCtrl.SerialWriteData(json.dumps(xArmGripper))


    def xArmHome(self):
        gripper_step = 200
        self.xArmPoseTxData(40, 0, 230)
        time.sleep(1)
        self.xArmGripperTxData(gripper_step)


    def main(self):
        rospy.spin()

    def shutdown(self):
        # Release handle to the webcam
        rospy.logwarn("now will shutdown xarm ...")


if __name__ == '__main__':
    rospy.init_node('abot_xarm_control')
    #os.system("rostopic pub -1 servo riki_msgs/Servo -- '90' '10'")
    node =AbotxArmGrasp()
    node.main()
